name: Automated Wine update
on:
  schedule:
    - cron:  '0 8 * * Sat'
  workflow_dispatch:

jobs:
  updateWine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Get Latest Wine Version
        id: wine
        run: |
          echo ::set-output name=release_tag::$(curl -sL https://www.winehq.org/news/ |grep "The Wine development release" |head -n1|cut -d " " -f5)
          echo ::set-output name=current_tag::$(grep "WINE_VERSION = " Makefile|cut -d' ' -f3)
      - name: Update Wine
        if: steps.wine.outputs.current_tag != steps.wine.outputs.release_tag
        env:
          RELEASE_TAG: ${{ steps.wine.outputs.release_tag }}
        run: |
            sed -i "s:^WINE_VERSION = .*$:WINE_VERSION = $RELEASE_TAG:" Makefile
            make build
      - name: Login to docker hub
        if: steps.wine.outputs.current_tag != steps.wine.outputs.release_tag
        uses: actions-hub/docker/login@master
        env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image
        if: steps.wine.outputs.current_tag != steps.wine.outputs.release_tag
        uses: actions-hub/docker@master
        with:
          args: push panard/wine:${{ steps.wine.outputs.release_tag }}-wow64
      - name: Push
        env:
          RELEASE_TAG: ${{ steps.wine.outputs.release_tag }}
        if: steps.wine.outputs.current_tag != steps.wine.outputs.release_tag
        run: |
            git tag wine-$RELEASE_TAG
            git add Makefile
            git commit -m "update to wine $RELEASE_TAG"
            git push
            git push --tags
            make push
